server:
  host: 0.0.0.0
  port: 7700
  max_connections: 10
  connection_timeout: 300
  read_timeout: 60
  server_name: "localhost"

tls:
  cert_file: /home/alhammadi/Downloads/ARI/test-certs/server.crt
  key_file: /home/alhammadi/Downloads/ARI/test-certs/server.key
  ca_file: /home/alhammadi/Downloads/ARI/test-certs/ca.crt
  min_version: TLSv1.2
  verify_client: true

oracle:
  user: epp_user
  dsn: "localhost:1521/TEST"
  pool_min: 1
  pool_max: 5
  pool_increment: 1

epp:
  server_id: "Test EPP Server"
  roid_suffix: "TEST"
  supported_versions:
    - "1.0"
  supported_languages:
    - "en"
  supported_objects:
    - "urn:ietf:params:xml:ns:domain-1.0"
    - "urn:ietf:params:xml:ns:contact-1.0"
    - "urn:ietf:params:xml:ns:host-1.0"
  supported_extensions: []
